services:
  - type: web
    name: lms-system
    env: docker
    plan: free
    region: frankfurt
    healthCheckPath: /
    healthCheckMaxRetries: 15
    healthCheckInterval: 10000
    healthCheckTimeout: 10000
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://abi-lms.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_CHANNEL
        value: stderr
      - key: ADMIN1_EMAIL
        sync: false
      - key: ADMIN1_FIRST_NAME
        sync: false
      - key: ADMIN1_LAST_NAME
        sync: false
      - key: ADMIN1_PHONE
        sync: false
      - key: ADMIN1_PASSWORD
        sync: false
      - key: ADMIN2_EMAIL
        sync: false
      - key: ADMIN2_FIRST_NAME
        sync: false
      - key: ADMIN2_LAST_NAME
        sync: false
      - key: ADMIN2_PHONE
        sync: false
      - key: ADMIN2_PASSWORD
        sync: false
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp-relay.brevo.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: AB Inventech LMS
